//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gate.java
//  @ Date : 2021. 03. 11.
//  @ Author : 
//
//




public class Gate implements Transport {    // A teleportkaput reprezent�l� oszt�ly.
	private Asteroid asteroid;              //Az az aszteroida, amire a Gate p�ld�nyt elhelyezt�k.
	private Gate pair;                      //Az adott kapu p�rja. 
	public void SetPair(Gate g) {           //Be�ll�tja, hogy melyik kapup�r a p�rja.
	    System.out.println("SetPair()");
	    pair = g; 
	}
	
	public Gate GetPair() {                 //Visszaadja az adott kapu p�rj�t 
	    System.out.println("GetPair() : Gate");
	    return pair;
	}
	
	public void SetAsteroid(Asteroid a) {   //Be�ll�tja, hogy melyik aszteroid�n �ll a kapu.
	    System.out.println("SetAsteroid(Asteroid a)");
	    asteroid = a;
	}
	
	public Asteroid GetAsteroid() {        //Az asteroid param�ter �rt�k�t adja vissza.
	    System.out.println("GetAsteroid() : Asteroid");
	    return asteroid;
	}
	
	public void Transport(Creature c) {    //k�t aszteroida k�z�tti mozg�s teleportkapu �ltal
	    System.out.println("Transport(Creature c)");
	    asteroid.AddCreature(c);
		c.SetAsteroid(asteroid);

	}
}
