//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 03. 11.
//  @ Author : 
//
//


import java.util.ArrayList;

public class Robot extends Creature implements Steppable {

	public void WhereToMove() { //A robot eldönti, hogy melyik aszteroidára mozogjon
		Controller c = new Controller();
		c.InsertTab("WhereToMove()");

		ArrayList<Transport> a = asteroid.GetNeighbours(); //lekerdezi annak az aszteroidanak a szomszedait, amin epp all
		if(a==null) Die(); //ha nem tud hova menni (azaz az aszteroidanak, mar nincs szomszedja), akkor meghal
		else Move(a.get(0).GetAsteroid()); //a robot mozog
	}

	public int NextStep() {//a robot eldonti, hogy a kovetkezo lepesben mit csinaljon
		Controller c = new Controller();
		c.InsertTab("NextStep(): 0");

		return 0; //az egyszeruseg kedveert most csak 0-val ter vissza
	}

	public void Step() { //a robot vegrehajtja a kivalasztott muveletet
		Controller c = new Controller();
		c.InsertTab("Step()");

		int result = NextStep();
		if(result == 0) Drill();
		else if(result==1) WhereToMove();
	}
	
	public void Die() { // a robot meghal
		Controller c = new Controller();
		c.InsertTab("Die()");

		asteroid.RemoveCreature(this); //a robot kitorlodik az aszterodia creture listajabol
		asteroid.GetSpace().RemoveCreature(this); //a robot megkerdezi az aszteroidat, hogy melyik spaceben van és kitorlodik az space creture listajabol
		Game.getInstance().RemoveSteppable(this); //a robot kitorlodik az space steppable listajabol
	}
	
	public void Move(Asteroid a) { //a robot a kiavlasztott aszteroidara mozog
		Controller c = new Controller();
		c.InsertTab("Move(a)");

		asteroid.GetNeighbours(); //a robot megkapja, hogy melyik transport objektum fogja átvinni a másik aszteroidára
		a.Transport(this); //meghívja az objektum transport függvényét
		asteroid.RemoveCreature(this); //a robot kitorlodik az aszterodia creture listajabol
	}
	
	public void AsteroidExplosion() { //a robot reagál az aszteroida felrobbanására
		Controller c = new Controller();
		c.InsertTab("AsteroidExplosion()");

		WhereToMove();
	}
	
	public ArrayList<Material> GetMaterials() { //a robot megmondja, hogy milyen nyersanyagok vannak nala
		Controller c = new Controller();
		c.InsertTab("GetMaterials() : null");

		return null; // a robotnál nincs nyersanyag
	}
}
